// <auto-generated />
using System;
using ERP.PersistenceSQL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ERP.PersistenceSQL.Migrations
{
    [DbContext(typeof(SqlERPDbContext))]
    partial class SqlERPDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.14")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ERP.Domain.Entities.PersonaEntities.Persona", b =>
                {
                    b.Property<int>("nmid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("cddocumento")
                        .IsRequired()
                        .HasColumnType("VARCHAR(20)");

                    b.Property<string>("cdgenero")
                        .HasColumnType("VARCHAR(10)");

                    b.Property<string>("cdtelefono_movil")
                        .HasColumnType("VARCHAR(20)");

                    b.Property<string>("cdtelfono_fijo")
                        .HasColumnType("VARCHAR(20)");

                    b.Property<string>("cdtipo")
                        .HasColumnType("VARCHAR(10)");

                    b.Property<string>("cdusuario")
                        .HasColumnType("VARCHAR(150)");

                    b.Property<string>("dsapellidos")
                        .HasColumnType("VARCHAR(60)");

                    b.Property<string>("dsdireccion")
                        .HasColumnType("VARCHAR(200)");

                    b.Property<string>("dsemail")
                        .HasColumnType("VARCHAR(200)");

                    b.Property<string>("dsnombres")
                        .IsRequired()
                        .HasColumnType("VARCHAR(60)");

                    b.Property<string>("dsphoto")
                        .HasColumnType("VARCHAR(500)");

                    b.Property<DateTime>("febaja")
                        .HasColumnType("DATETIME");

                    b.Property<DateTime>("fenacimiento")
                        .HasColumnType("DATE");

                    b.Property<DateTime>("feregistro")
                        .HasColumnType("DATETIME");

                    b.HasKey("nmid");

                    b.ToTable("TblPersona", "General");
                });
#pragma warning restore 612, 618
        }
    }
}
